# Numpy Practice

In [39]:
import numpy as np

In [40]:
# 1. Create a 3x3 matrix filled with numbers from 1 to 9.

a = np.array([1,2])
a

array([1, 2])

In [41]:
a.shape

(2,)

In [42]:
seq = np.array(range(1,11))
seq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# expected ouput
# [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]

x = np.array(range(2,19,2)).reshape((3,3))


In [44]:
x

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [45]:
x.transpose()

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [46]:
x.trace()

np.int64(30)

In [47]:
matrix = np.random.randint(1,101,size=(3,3))

In [48]:
matrix

array([[51, 83, 73],
       [46, 43, 33],
       [ 3,  9,  8]], dtype=int32)

In [49]:
type(matrix)

numpy.ndarray

In [50]:
#matrix[matrix>50]=23

In [51]:
matrix

array([[51, 83, 73],
       [46, 43, 33],
       [ 3,  9,  8]], dtype=int32)

In [52]:
np.diag(matrix)

array([51, 43,  8], dtype=int32)

In [53]:
matrix.transpose()

array([[51, 46,  3],
       [83, 43,  9],
       [73, 33,  8]], dtype=int32)

In [54]:
np.flip(matrix)

array([[ 8,  9,  3],
       [33, 43, 46],
       [73, 83, 51]], dtype=int32)

In [55]:
np.fliplr(matrix)

array([[73, 83, 51],
       [33, 43, 46],
       [ 8,  9,  3]], dtype=int32)

In [56]:
np.fliplr(matrix).diagonal()

array([73, 43,  3], dtype=int32)